// Deterministic audio clip metadata. The WAV files are generated by
// scripts/generate-audio.mjs from this same metadata so durations always match.
//
// The audio source behind these URLs is a placeholder for a future TTS pipeline;
// the player contract (id/title/source/duration/audioUrl) is unchanged by that swap.

export const CLIPS = [
  { file: 'nuzio-1.wav', duration: 18 },
  { file: 'nuzio-2.wav', duration: 24 },
  { file: 'nuzio-3.wav', duration: 12 },
  { file: 'nuzio-4.wav', duration: 30 },
]

export function stableHash(input) {
  let hash = 0
  const str = String(input)
  for (let i = 0; i < str.length; i += 1) {
    hash = (hash * 31 + str.charCodeAt(i)) | 0
  }
  return Math.abs(hash)
}

// Pick the same clip for the same story deterministically.
export function pickClip(articleId) {
  const index = stableHash(articleId) % CLIPS.length
  return CLIPS[index]
}

// Attach the audio contract to ranked articles using a request-derived base URL,
// exposing the frontend-friendly `id` on each story.
export function attachAudio(articles, baseUrl) {
  return articles.map((article, index) => {
    const clip = pickClip(article.externalId)
    return {
      id: article.externalId,
      title: article.title,
      description: article.description,
      content: article.content,
      imageUrl: article.imageUrl,
      source: article.source,
      url: article.url,
      category: article.category,
      topics: article.topics,
      language: article.language,
      publishedAt: article.publishedAt,
      audioUrl: `${baseUrl.replace(/\/$/, '')}/audio/${clip.file}`,
      duration: clip.duration,
      isTopStory: index === 0,
    }
  })
}