import express from 'express'
import helmet from 'helmet'
import cors from 'cors'
import morgan from 'morgan'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

import authRoutes from './modules/auth/auth.routes.js'
import userRoutes from './modules/users/user.routes.js'
import newsRoutes from './modules/news/news.routes.js'
import { errorHandler } from './middleware/index.js'
import config from './config/index.js'

const app = express()

app.use(helmet())
app.use(cors({ origin: config.clientOrigin }))
app.use(express.json())
app.use(morgan('dev'))

// Audio clips used by the player's audio contract (config.audio.baseUrl or the
// request origin resolves to this path). Generated by scripts/generate-audio.mjs.
// The scoped helmet override relaxes Cross-Origin-Resource-Policy so the browser
// may embed audio served from a different origin than the app (dev: 5173 -> 5000,
// or a future CDN via AUDIO_BASE_URL). The API keeps helmet's strict default.
const audioDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'audio')
app.use(
  '/audio',
  helmet.crossOriginResourcePolicy({ policy: 'cross-origin' }),
  express.static(audioDir, { maxAge: '1y', immutable: true }),
)

app.get('/health', (req, res) => {
  res.json({ status: 'ok' })
})

app.use('/api/auth', authRoutes)
app.use('/api/users', userRoutes)
app.use('/api/news', newsRoutes)

app.use(errorHandler)

export default app